### ISSUE TITLE
Rename deleted_at to deletedAt

### ISSUE THREAD

**Issue by DZ8540** [lookinlab/adonis-lucid-soft-deletes#11]
Hi, in my project, all models uses camel case naming strategy by default, and i need to rename deleted_at to deletedAt column, how can i rename this column in my model?

My migration file:
<img width="691" alt="image" src="https://user-images.githubusercontent.com/50152205/170214990-3272e69f-f492-45c1-8abc-ec456673a642.png">

My model file (rename column via columnName property in decorator not helped and worked):
<img width="335" alt="image" src="https://user-images.githubusercontent.com/50152205/170215230-006c3e9e-c3d6-45a2-9df2-3d589860a9ae.png">

Error:
<img width="494" alt="image" src="https://user-images.githubusercontent.com/50152205/170215440-9c9495ec-d22e-44fd-bdcb-1b7951e3dba6.png">

Thanks!

**Comment by LookinGit** [comment]
Hello @DZ8540 
Now you can’t set custom column name, but I’ll think about it in the coming days.

**Comment by LookinGit** [comment]
Added in v1.4.0
