### ISSUE TITLE
Breaks where in related query

### ISSUE THREAD

**Issue by atharahmed** [lookinlab/adonis-lucid-soft-deletes#12]
Hi,

Recently I updated Adonis, Lucid, and soft-deletes to their latest versions, and now where query in preload is broken.

Following are the version updates:

`@adonisjs/core               ^5.5.3  →   ^5.8.3`
`@adonisjs/lucid             ^17.1.0  →  ^18.0.0`
`adonis-lucid-soft-deletes    ^1.3.3  →   ^1.4.1`

I get the "Cannot read properties of undefined (reading 'method')" error.

So I inspected to find the error and seems like the issue is caused by the `toQuery()` method on line 32 of the following file:
https://github.com/lookinlab/adonis-lucid-soft-deletes/blob/develop/src/SoftDeletes/index.ts

Replacing `const isGroupLimitQuery = query.toQuery().includes('adonis_group_limit_counter')` with
`let sqlQuery = query.toSQL().toNative()`
`const isGroupLimitQuery = sqlQuery.sql.includes('adonis_group_limit_counter');` seem to fix the issue.

I can create a PR if that helps.

Thanks

**Comment by LookinGit** [comment]
Hi @atharahmed 
Can you send callstack of error "Cannot read properties of undefined (reading 'method')"?

**Comment by atharahmed** [comment]
Please see attached image:

<img width="1440" alt="Screenshot 2022-05-28 at 10 42 27 PM" src="https://user-images.githubusercontent.com/7909423/170836863-fe36cf50-ff6d-4708-a252-f8300b10a06a.png">

I'm trying to test the suggested fix a fork of the package.

**Comment by LookinGit** [comment]
I don`t think what replace `toQuery` to `toSQL` will fix this issue. Both methods call `applyWhere()` where this error occurs

Need check why `firstItem` is undefined.

**Comment by atharahmed** [comment]
My suggested fix does not work but it seems like when you transform the lucid object to SQL query it adds an empty array in chainable of lucid which throws the error.

You can recreate the issue by replacing `.preload('authors', (authors) => authors.groupLimit(2))` with `.preload('authors', (authors) => authors.where('name', 'John'))` in `relations.spec.ts` file line 226

**Comment by LookinGit** [comment]
Fixed in v1.4.2
