### ISSUE TITLE
Wrong interfaces for ignoreDeleted and ignoreDeletedPaginate methods

### ISSUE THREAD

**Issue by KageNoNeko** [lookinlab/adonis-lucid-soft-deletes#14]
These interfaces describe both methods as if they had no parameters:
https://github.com/lookinlab/adonis-lucid-soft-deletes/blob/79288ecd984b9ff604a5dc84a1a657a5dd0492df/adonis-typings/querybuilder.ts#L11-L13
https://github.com/lookinlab/adonis-lucid-soft-deletes/blob/79288ecd984b9ff604a5dc84a1a657a5dd0492df/adonis-typings/mixin.ts#L17-L20

But they actually have one:
https://github.com/lookinlab/adonis-lucid-soft-deletes/blob/79288ecd984b9ff604a5dc84a1a657a5dd0492df/src/SoftDeletes/index.ts#L26-L28
https://github.com/lookinlab/adonis-lucid-soft-deletes/blob/79288ecd984b9ff604a5dc84a1a657a5dd0492df/src/SoftDeletes/index.ts#L41

**Prerequisites**

- "@adonisjs/lucid": "18.0.0"
- "adonis-lucid-soft-deletes": "1.4.3"

**Comment by LookinGit** [comment]
Fixed v1.4.4
