### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by wallysonn** [lookinlab/adonis-lucid-soft-deletes#16]
A 'deletedAt' property on type 'User' cannot be assigned to the same property on base type 'LucidRow & { $forceDelete: boolean; DeletedIn: DateTime | null; read-only discarded: boolean; $getQueryFor(action: "insert", client: QueryClientContract): InsertQueryBuilderContract<...>; $getQueryFor(action: "update" | ... 1 more ... | "update", client: QueryClientContract): ModelQueryBuilderContract<...>; delete(): ...'.

**Comment by wallysonn** [comment]
Any ideas on how to get around this problem? I'm using Adonis 5

**Comment by LookinGit** [comment]
@wallysonn remove `?` for column `deletedAt`:

Before:

```ts
@column.dateTime({ columnName: 'customDeletedAtColumn' })
public deletedAt?: DateTime | null
```

After:

```ts
@column.dateTime({ columnName: 'customDeletedAtColumn' })
public deletedAt: DateTime | null
```
