### ISSUE TITLE
Error on Global Hook

### ISSUE THREAD

**Issue by wallysonn** [lookinlab/adonis-lucid-soft-deletes#19]
When trying to use Hook Global using the model presented in the link ([https://adocasts.com/lessons/how-to-use-adonisjs-model-hooks-to-log-all-user-actions](https://adocasts.com/lessons/how-to-use-adonisjs-model-hooks-to-log-all-user-actions)), all queries made in models that use softdelete returns the error (`select * from model_with_soft_deletes...`), where it changes the real table name to **model_with_soft_deletes**. Any idea how I can solve it? Thank's for your time.

**Comment by LookinGit** [comment]
Hi @wallysonn. This addon not tested for use in Global Hooks and not intended for BaseModel. Addon need use on specific model
