### ISSUE TITLE
Lucid v21 support

### ISSUE THREAD

**Issue by padinko** [lookinlab/adonis-lucid-soft-deletes#22]
What is plan for supporting [@adonisjs/lucid](https://github.com/adonisjs/lucid) v21?
[changes](https://github.com/adonisjs/lucid/releases/tag/v21.0.0)

**Comment by LookinGit** [comment]
Hi, new changes not includes breaking changes. You can use as before.

**Comment by padinko** [comment]
"peerDependencies" do not allow installation of this package

**Comment by LookinGit** [comment]
@padinko thanks, updated v2.1.0
