### ISSUE TITLE
total in paginate is false

### ISSUE THREAD

**Issue by Barbapapazes** [lookinlab/adonis-lucid-soft-deletes#3]
Hello, 

When using the paginate function, the total counts the deleted record. So, in a database of 3 users with one deleted. Total will be 3 instead of 2 !

To fixed, we need to refer to [the documentation](https://docs.adonisjs.com/guides/models/hooks#beforepaginate)

A pull request is ready to fix this issue (will be created after you accept #2) and a reproduction repository can be found [here](https://github.com/Barbapapazes/adonis-soft-deletes-issue)

Thanks for you works!

**Comment by LookinGit** [comment]
Hi @Barbapapazes!
Thanks for issue and PR. I fixed this.
Sorry, i didn`t want to add a `prettier`.

**Comment by Barbapapazes** [comment]
Thanks for this fast fix
