### ISSUE TITLE
Add deleted_at in where to link tables

### ISSUE THREAD

**Issue by nurycaroline** [lookinlab/adonis-lucid-soft-deletes#7]
Hi
When using preload, I think that deleted_at should be added to all tables involved.
For example, if a link between book and author is removed, the search will still bring the link, because the deleted_at is for the Book table, I think I should add it to the author_book table as well.

**Comment by LookinGit** [comment]
Hello :)
In this case may be use a HasManyThrough relation. Create a model AuthorBook with soft deletes.
Not sure for this solution, need try and test
